### ISSUE TITLE
uint32_t is not defined in zconf.h

### ISSUE THREAD

**Issue by danyspin97** [zlib-ng/zlib-ng#1342] opened 2022-09-08 10:15 UTC
In ff9162c1a0da8d60ae664e5930b256de99ad83b3, `z_crc_t` type has been added as `uint32_t`. However, `uint32_t` is not defined in zconf.h. zlib's zconf.h uses some macros to select the correct type of integer for `z_crc_t`, so stdint.h does not need to be included. But when using `z_crc_t` in zlib-ng, stdint.h must be included, causing compatibility issues between zlib-ng and zlib.

```
[   98s] gcc -DHAVE_CONFIG_H -I.  -include config.h -I./include -DLOCALEDIR=\"/usr/share/locale\" -D_PATH_RUNSTATEDIR=\"/run\" -D_PATH_SYSCONFSTATICDIR=\"/usr/lib\" -D_PATH_VENDORDIR=\"/usr/etc\"   -fsigned-char -fno-common -Wall -Wextra -Waddress-of-packed-member -Wdiscarded-qualifiers -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-missing-field-initializers -Wpointer-arith -Wredundant-decls -Wsign-compare -Wstrict-prototypes -Wtype-limits -Wuninitialized -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-parameter -Wunused-result -Wunused-variable -Werror=sequence-point -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -ffat-lto-objects -D_GNU_SOURCE -c -o disk-utils/mkfs.cramfs.o disk-utils/mkfs.cramfs.c
[   98s] In file included from disk-utils/mkfs.cramfs.c:38:
[   98s] /usr/include/zconf.h:130:9: error: unknown type name 'uint32_t'
[   98s]   130 | typedef uint32_t z_crc_t;
[   98s]       |         ^~~~~~~~
[   98s] make[2]: *** [Makefile:9393: disk-utils/mkfs.cramfs.o] Error 1
[   98s] make[2]: *** Waiting for unfinished jobs....
[   98s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/util-linux-2.37.4'
[   98s] make[1]: *** [Makefile:14432: all-recursive] Error 1
[   98s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/util-linux-2.37.4'
[   98s] make: *** [Makefile:6254: all] Error 2
```

The error happened while building util-linux-2.37.4 in a staging project for openSUSE Tumbleweed, using latest develop branch.

**Comment by mtl1979** [comment] 2022-09-08 10:52
Fixing this isn't easy as the standard headers must be included in specific order, otherwise the compilation will fail when building zlib-ng. As such, the issue must be fixed first in the headers distributed by the compilers before we can fix the issue in zlib-ng.

zlib-ng doesn't guarantee 100% source compatibility or that it can be compiled without changes using any of the common or uncommon compilers. Some changes we have introduced were for catching errors that zlib silently ignores and would cause unexpected behavior, including incorrect results due to integer widths being wider on 64-bit platforms... zlib itself supports only 16-bit and 32-bit platforms and does give no guarantee that it works correctly on 64-bit platforms.

**Comment by nmoinvaz** [comment] 2022-09-11 12:59
We can change to `unsigned int`..

**Comment by mtl1979** [comment] 2022-09-11 13:11
@nmoinvaz Changing it back to `unsigned int` would violate our style guide, but I guess that's inevitable if we want to avoid depending on broken system headers. If somebody tries to compile zlib-ng on system where it isn't exactly 32-bits, a lot more will likely be broken.

**Comment by danyspin97** [comment] 2022-09-12 08:28
This is the relevant snippet from zlib:

```
#if !defined(Z_U4) && !defined(Z_SOLO) && defined(STDC)
#  include <limits.h>
#  if (UINT_MAX == 0xffffffffUL)
#    define Z_U4 unsigned
#  elif (ULONG_MAX == 0xffffffffUL)
#    define Z_U4 unsigned long
#  elif (USHRT_MAX == 0xffffffffUL)
#    define Z_U4 unsigned short
#  endif
#endif

#ifdef Z_U4
   typedef Z_U4 z_crc_t;
#else
   typedef unsigned long z_crc_t;
#endif
```

They are not using `unsigned long` unconditionally though.

Which is the issue in the compiler headers that you are referring to?

**Comment by mtl1979** [comment] 2022-09-12 08:48
> Which is the issue in the compiler headers that you are referring to?

Including `stdarg.h` before `stdint.h` will cause compiler errors, because the headers have circular dependency. This will be an issue when a function has variadic arguments.

**Comment by nmoinvaz** [comment] 2022-11-12 15:51
This has been resolved in the develop branch.

**Closed as completed by nmoinvaz** 2022-11-12 15:51 UTC
Labels: Compatibility
