### ISSUE TITLE
zlib-ng in compat mode cannot extract zopfli compressed

### ISSUE THREAD

**Issue by concatime** [zlib-ng/zlib-ng#1007] opened 2021-06-18 19:42 UTC
When building pigz with zlib-ng in compat mode, I get `pigz: skipping: ./archive.dir.tar.gz: corrupted -- crc32 mismatch`.

Step to reproduce:
```sh
curl -LO 'https://github.com/zlib-ng/zlib-ng/files/6679001/archive.dir.tar.gz'
gunzip ./archive.dir.tar.gz
./pigz -c -11 ./archive.dir.tar > ./archive.dir.tar.gz # may take some time
./pigz -cd ./archive.dir.tar.gz >  ./archive.dir.2.tar # fails
/usr/bin/pigz -cd ./archive.dir.tar.gz >  ./archive.dir.3.tar # succeeds (system’s pigz is built with normal zlib)
gzip -cd ./archive.dir.tar.gz > ./archive.dir.4.tar # succeeds
```
[archive.dir.tar.gz](https://github.com/zlib-ng/zlib-ng/files/6679001/archive.dir.tar.gz)

**Comment by nmoinvaz** [comment] 2021-06-18 20:39
Seems like a duplicate of #979.

**Comment by mtl1979** [comment] 2021-06-22 12:07
Should retest with latest develop tree... It has several fixes merged in.

**Comment by Dead2** [comment] 2021-06-22 12:42
Please test `Stable` branch instead, that is the one containing only the fixes for the planned 2.0.5 release.

**Comment by mtl1979** [comment] 2021-06-22 13:31
@Dead2 Obviously testing `stable` branch works after you have cherry-picked the commits, pushed them to GitHub and GitHub has synced the repository.... There is slight delay after pushing, before the commit(s) show up in `git fetch`. This is obvious if you try to push to same branch or repository too fast in succession. It won't let you until the repository is synced. When you modify a repository on GitHub, it doesn't just modify that single repository, it will repackage all forked and parent repositories too.

**Comment by Dead2** [comment] 2021-06-22 13:34
@mtl1979 `Stable` is where 2.0.5 is being staged, and has been for days. And testing develop might encounter different bugs or fixes since they are diverging.

**Comment by mtl1979** [comment] 2021-06-22 13:36
@Dead2 That's why I'm mentioning you in fixes that might affect or are relevant also to `stable` branch.

**Comment by nmoinvaz** [comment] 2021-09-04 16:49
I am not able to reproduce this with the latest stable version. I used pigz built with zlib-ng and testing it against the `archive.dir.tar.gz` file provided.

If you continue to have issues please reopen.

**Closed as completed by nmoinvaz** 2021-09-04 16:49 UTC

**Comment by concatime** [comment] 2021-09-07 19:12
Understood, will test soon and report if any issue raises.
