### ISSUE TITLE
Invalid gzip stream produced for compression level = 1

### ISSUE THREAD

**Issue by ztlpn** [zlib-ng/zlib-ng#81] opened 2017-01-10 16:43 UTC
Hi. I've noticed that the algorithm for compression level 1 sometimes produces invalid gzip stream. I've created a fork containing the test case: https://github.com/ztlpn/zlib-ng. It consists of a file with input data and tweaked buffer sizes in minigzip.c.

Steps to reproduce:
1. `./configure && make`
2. `cat test.in | ./minigzip -c -1 | gzip -d > /dev/null`

gzip then fails with the following message: `gzip: stdin: invalid compressed data--format violated`

The output of ./configure:
```
Checking for shared library support...
Building shared library libz.so.1.2.8.zlib-ng with gcc-5.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking for ANSI C compliant compiler...  Yes.
Checking for attribute(visibility(hidden)) support... Yes.
Checking for attribute(visibility(internal)) support... Yes.
Checking for __builtin_ctzl ... Yes.
Checking for SSE2 intrinsics ... Yes.
Checking for PCLMULQDQ intrinsics ... Yes.
ARCH: x86_64
Using arch directory: arch/x86
```

**Comment by ztlpn** [comment] 2017-01-17 10:21
@Dead2 Have you been able to reproduce?

**Comment by silviucpp** [comment] 2017-01-17 11:05
I have the same problem in my app.

**Comment by Dead2** [comment] 2017-01-17 14:30
I have unfortunately been swamped with work lately, although I am slowly making headway with the backlog. Hopefully I will have some spare time to spend on zlib-ng soon. I can honestly say that not a day goes by without me thinking about zlib-ng.

That said, I suggest you check out the code from Intel's fork of zlib, since that is where the deflate-quick (level 1 of zlib-ng) comes from. We have made only very minor changes to that part of the code, partially because it is quite a bit harder to understand and modify than the stock zlib code. I also see that they have made 3 commits that likely have not been imported to zlib-ng yet, so if one of those fixes this problem then I would be very interested in knowing so.
And if the problem still exists in intel's fork, then opening an issue there with a test-case such as the one you made for zlib-ng is probably the most likely to result in a fix, and they will probably appreciate having a reproducible test-case such as you have made. They have had several reports of such problems, but often without good test-cases, making it nearly impossible to find the bug(s), and this might be one of the bugs they have not managed to nail down yet.

I am sorry I can not be of more help right now, but thank you for taking the time to contribute your problem report.

**Comment by silviucpp** [comment] 2017-01-17 15:39
Hello,

I tested now my use case with intel fork and seems fine. I can't replicate my problem there. 

UPDATE: I was wrong. seems issue persist also on intel's fork but with other data set

Silviu

**Comment by ztlpn** [comment] 2017-01-17 15:47
Ok, thanks for the reply! I will try to investigate some more. Maybe I will be able to zero in on the root cause just by comparing patches even without understanding much about zlib internals.

As for now, I think it would be advisable to switch deflate-quick off by default as the simplest fix.

**Comment by Dead2** [comment] 2017-01-18 13:10
I'd also suggest testing the patches in https://github.com/jtkukunas/zlib/pull/14
If those fix the problem (would be great to know which of the commits as well), then I'd be inclined to pull those even though Intel has not had time to review them yet.

Just to clarify, remember to test without their last commit "temporarily remove deflate_quick from default config". That commit disables deflate_quick completely and would invalidate any testing :)

**Comment by ztlpn** [comment] 2017-01-26 13:27
Ok, I've tested with the Intel fork. The problem is present there, introduced in https://github.com/jtkukunas/zlib/commit/d948170e11e4eaa68cce189e5ea10a4d41e01437 (the commit introducing deflate_quick strategy).

The patches in jtkukunas/zlib#14 seem to help.

**Comment by Dead2** [comment] 2017-01-30 14:37
I have merged those (and a lot of other backlogged commits) to the hacknslash4 branch, would you please test whether the problem is fixed now?

More of the backlogged upstream zlib commits will be merged soon hopefully.

**Comment by Dead2** [comment] 2017-02-13 14:00
hacknslash5 has been merged into the develop branch, closing

**Closed as completed by Dead2** 2017-02-13 14:00 UTC
