### ISSUE TITLE
nss build failure when using --zlib-compat (API incompatability?)

### ISSUE THREAD

**Issue by MilhouseVH** [zlib-ng/zlib-ng#481] opened 2019-11-25 17:23 UTC
The Mozilla package [nss](https://github.com/nss-dev/nss) (latest 3.47.1 release) builds against upstream `zlib-1.2.11` but fails to build against latest `zlib-ng` 5bd3c582908503135fd8d6326ca0e2a6a947b44f with  `--zlib-compat` enabled:
```
/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/bin/host-gcc -o Linux4.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/zip.o -c -O2 -fPIC  -m64 -pipe -ffunction-sections -fdata-sections -DHAVE_STRERROR -DLINUX -Dlinux -Wall -Wshadow -Werror -DXP_UNIX -UDEBUG -DNDEBUG -D_REENTRANT -DNSS_NO_INIT_SUPPORT -DUSE_UTIL_DIRECTLY -DNO_NSPR_10_SUPPORT -DSSL_DISABLE_DEPRECATED_CIPHER_SUITE_NAMES -I/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/include -I/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/include/nspr -I./../dist/Linux4.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/include -I./../dist/public/ -I./../dist/private/ -I/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/include/nspr -I../../dist/Linux4.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/include -I../../dist/public/ -I../../dist/private/ -I../../dist/public/nss -I../../dist/public/nspr -I../../dist/public/libdbm -I../../dist/Linux4.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/../public/security -I./include  -I/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/include/nspr -I../../../dist/Linux4.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/include -I../../../dist/public/nss -I../../../dist/private/nss -I../../../dist/public/seccmd  zip.c
zip.c: In function 'JzipAdd':
zip.c:325:28: error: passing argument 2 of 'handle_zerror' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
         handle_zerror(err, zstream.msg);
                            ^
zip.c:92:1: note: expected 'char *' but argument is of type 'const char *'
 handle_zerror(int err, char *msg)
 ^
zip.c:335:36: error: passing argument 2 of 'handle_zerror' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
                 handle_zerror(err, zstream.msg);
                                    ^
zip.c:92:1: note: expected 'char *' but argument is of type 'const char *'
 handle_zerror(int err, char *msg)
 ^
zip.c:368:32: error: passing argument 2 of 'handle_zerror' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
             handle_zerror(err, zstream.msg);
                                ^
zip.c:92:1: note: expected 'char *' but argument is of type 'const char *'
 handle_zerror(int err, char *msg)
 ^
zip.c:464:28: error: passing argument 2 of 'handle_zerror' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
         handle_zerror(err, zstream.msg);
                            ^
zip.c:92:1: note: expected 'char *' but argument is of type 'const char *'
 handle_zerror(int err, char *msg)
 ^
cc1: all warnings being treated as errors
make[3]: *** [../../coreconf/rules.mk:393: Linux4.4_x86_64_gcc_glibc_PTH_64_OPT.OBJ/zip.o] Error 1
make[3]: Leaving directory '/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/nss-3.47.1/nss/cmd/signtool'
make[2]: *** [../coreconf/rules.mk:101: libs] Error 2
make[2]: Leaving directory '/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/nss-3.47.1/nss/cmd'
make[1]: *** [coreconf/rules.mk:101: libs] Error 2
make[1]: Leaving directory '/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/nss-3.47.1/nss'
```
Tail end of build log: http://ix.io/22Pz

The following `nss` patch is a temporary workaround to build `nss` against `zlib-ng` (I think it works - I'm not a C-coder!) but presumably this `nss` change should not be necessary in `--zlib-compat` mode:
```
diff --git a/nss/cmd/signtool/zip.c b/nss/cmd/signtool/zip.c
index aeb5d6c..82f7ac5 100644
--- a/nss/cmd/signtool/zip.c
+++ b/nss/cmd/signtool/zip.c
@@ -89,7 +89,7 @@ my_free_func(void *opaque, void *address)
 }

 static void
-handle_zerror(int err, char *msg)
+handle_zerror(int err, const char *msg)
 {
     if (!msg) {
         msg = "";
```

This build failure is present when building `nss` for the x86_64 host (using the "system" zlib ie. `zlib-ng`), so it is not a cross-compile issue.

LibreELEC `nss-3.47.1` build package: https://github.com/LibreELEC/LibreELEC.tv/pull/4022
LibreELEC `zlib-ng` test branch: https://github.com/LibreELEC/LibreELEC.tv/compare/master...MilhouseVH:le10_zlib-ng (depends on https://github.com/LibreELEC/LibreELEC.tv/pull/4023)

**Comment by MilhouseVH** [comment] 2019-11-25 17:38
Forgot to mention, `gcc` is 9.2.0.

**Comment by mtl1979** [comment] 2019-11-25 20:02
That code snippet is invalid and gcc is correct when it triggers an error. You can't assign string literal to non-const pointer as it would make non-local variable appear out of its scope.

**Comment by MilhouseVH** [comment] 2019-11-25 20:35
Thanks but as I say, I'm not a C-coder and I just wanted a quick & dirty fix in order to progress the rest of the distro build (so that I could find any other issues, which I now have).

Obviously the ABI breakage is the bigger issue, and I've raised a couple of other issues along the same lines with other packages.

A github "ABI Break" label might be useful!

**Comment by mtl1979** [comment] 2019-11-25 20:51
I'm just reiterating the reasons why there is some differences that we are unlikely to "unfix" even if that means our API is not 100% drop-in replacement. The rest might be fixed by people who are more familiar with the code.

**Comment by dhewg** [comment] 2019-11-25 20:52
gcc is triggering an error because `z_stream.msg` is const in zlib-ng, where it's non-const in zlib per default (unless `ZLIB_CONST` is set). That's arguably not zlib compatible even when using `--zlib-compat`.

As for the snippet, it's setting a non-const local pointer to a pointer somewhere in `.rodata`. That's not invalid. Also, it's mozilla, it compile tested on your toaster.

**Comment by Dead2** [comment] 2019-11-25 22:02
This makes me wonder why ZLIB_CONST is not set for stock zlib, probably another example of legacy code being used instead of the (slightly) more modern code.

We'll need to add some workarounds for compat mode, so compat mode uses zlib-compatible function definitions and types.

**Comment by mtl1979** [comment] 2019-11-25 22:59
@dhewg The issue is in code lines:
```
if (!msg) {
         msg = "";
```

This is only valid when msg is "const char *" because in that case compiler makes sure the string literal is copied if the value is not overwritten when the scope exits the function.

**Comment by dhewg** [comment] 2019-11-26 05:24
@mtl1979 I'm not sure about invalid, maybe weird or oldschool ;) It's still accepted by C compilers (there's `-Wwrite-strings` to catch those). In any case, there's no string literals being copied, it's just a function-scope pointer assignment.

But back to the issue, nss could also just be fixed to make it `ZLIB_CONST` compatible?

**Comment by mtl1979** [comment] 2019-11-26 05:31
@dhewg Converting string literals to "char *" is deprecated and as such invalid when using strict validation rules.

**Comment by dhewg** [comment] 2019-11-26 05:35
That I can agree with :D
Now zlib-ng has to decide if it want's to be compatible with that deprecated way (which is unfortunately the default for zlib) or if it want to be just `ZLIB_CONST` compatible.

**Comment by mtl1979** [comment] 2019-11-26 05:39
zlib-ng clearly has limit for how old compilers we are going to support... That conversion has been deprecated since early gcc 4.x builds, so clearly far beyond what we have planned supporting... Currently we do not support any compiler older than 2013...

**Comment by nmoinvaz** [comment] 2022-03-27 02:03
This should have been resolved in https://github.com/zlib-ng/zlib-ng/pull/704 and is already in all versions of zlib-ng that have been released. If there is still an issue please reopen.

**Closed as completed** 2022-03-27 02:06 UTC
Labels: Build Env
