### ISSUE TITLE
crash in fill_window_sse.lo under windows/mingw32

### ISSUE THREAD

**Issue by cieplutki** [zlib-ng/zlib-ng#173] opened 2018-04-21 19:29 UTC
Hello, I tried to test zlib-ng library in some gzip compressor that uses zlib. By chance I picked [pigz](http://zlib.net/pigz/), configured the library (with *--zlib-compat* ) and compiled under msys/mingw32/x86. With first try of using it it crashed. Didn't test with x64 windows as my computer is apart and I use spare one, although I test it under 32 bit linux, on the same computer, and it works, same with 64 bit - works as well.
After rather long and boring investigation I found that it happens in *fill_window_sse.lo* object. I found it in ollydbg and gdb and confirmed the code in binary object. 
It looks like this: (I attached my findings in more detailed way).
[fill_window_sse.o.crash.gz](https://github.com/Dead2/zlib-ng/files/1934939/fill_window_sse.o.crash.gz)

```asm
62E8EEBC   $ 55             PUSH EBP                                 ;; beginning of func? (fill_window_sse:?)
62E8EEBD   . 57             PUSH EDI
62E8EEBE   . 56             PUSH ESI
62E8EEBF   . 53             PUSH EBX
62E8EEC0   . 83EC 3C        SUB ESP,3C
62E8EEC3   . 8B5C24 50      MOV EBX,DWORD PTR SS:[ESP+50]
62E8EEC7   . 8BAB 80000000  MOV EBP,DWORD PTR DS:[EBX+80]
62E8EECD   . 66:0F6EC5      MOVD MM0,EBP
62E8EED1   . 66:0F61C0      PUNPCKLWD MM0,MM0
62E8EED5   . 66:0F70C0 00   PSHUFW MM0,MM0,0
62E8EEDA   . 8B83 C8000000  MOV EAX,DWORD PTR DS:[EBX+C8]
62E8EEE0   . 8D542D 00      LEA EDX,DWORD PTR SS:[EBP+EBP]
62E8EEE4   . 895424 2C      MOV DWORD PTR SS:[ESP+2C],EDX
62E8EEE8   . 89EE           MOV ESI,EBP
62E8EEEA   . 8D95 FAFEFFFF  LEA EDX,DWORD PTR SS:[EBP-106]
62E8EEF0   . 895424 28      MOV DWORD PTR SS:[ESP+28],EDX
62E8EEF4   . 66:0F7F4424 10 MOVQ QWORD PTR SS:[ESP+10],MM0           ;; <- crash here @ offset 0x000000f2 in fill_window_sse.lo
62E8EEFA   . E9 B1000000    JMP zlib1.62E8EFB0                       ;; 0x62E8EFB0-0x62E80000=0xEFB0, ?
62E8EEFF     90             NOP
62E8EF00   > 8B0B           MOV ECX,DWORD PTR DS:[EBX]
62E8EF02   . 8B71 04        MOV ESI,DWORD PTR DS:[ECX+4]
62E8EF05   . 85F6           TEST ESI,ESI
62E8EF07   . 0F84 4B010000  JE zlib1.62E8F058
```
Despite my efforts I couldn't pin down where exactly in fill_window_sse.c this crash happens, all the more to solve the issue.
What am I to do to solve it or find the problem so it can be solved?
PS. Although this computer is a bit old it suppose to support SSE/2/3.

**Comment by Dead2** [comment] 2018-04-21 20:17
Did you compile pigz against the resulting zlib-ng library, or was it compiled against stock zlib?
Even with zlib-compat mode, it is unfortunately not ABI-compatible, only API-compatible.

**Comment by cieplutki** [comment] 2018-04-22 23:08
I compiled and linked it against zlib-ng (1.9.9/1.2.11.zlib-ng), with zlib (1.2.5 and 1.2.11 that I tested) there is no such error.
I edited Makefile so it wouldn't use *-llib* but rather linked against object like 
```
ZLIB_DIR = ../../zlib-ng/zlib-ng-1.9.9-develop
# for static link
LIBS = -lm -lpthread $(ZLIB_DIR)/bin/zlib-ng-1.9.9--zlib-compat--static/libz.a
# for shared link
LIBS = -lm -lpthread $(ZLIB_DIR)/bin/zlib-ng-1.9.9--zlib-compat--shared/zlib1.dll
```
In both static and shared linked programs segfault appears in the same place in code. As I said details are in attached file. Also tested it under linux and it's seems perfectly fine there - it compresses input and producing correct output without any unhealthy symptoms. There have to be some smart way to find out what is the cause.

**Comment by Dead2** [comment] 2018-04-23 11:08
Thanks for confirming, we just don't want to waste time debugging an issue where there is a known incompatibility :)
Would you be able to provide the configure and make logs? Also, if you have time, could you check whether disabling the new compression strategies (during configure) makes any difference? And last, does it make any difference what compression level pigz is run with? 1,4,6,8 should trigger all the different strategies.

**Comment by cieplutki** [comment] 2018-04-24 16:44
Hey, I have uploaded files you asked. They are on on wikisend to not clutter forum. If it's necessary I will put them here or in some more permanent storage. Just didn't have too much time.
[makefiles and logs](https://drive.google.com/open?id=1VStGsQPQi_WZulcMhHrEgZSkvI2xbl3o), whole [compilation of zlib-ng](https://drive.google.com/file/d/1FmvZ6nhOwS02w3WQIh1StmMC_8h5A62t) and even [pigz linked with the library](https://drive.google.com/file/d/11qfVoll8p4hvBzR0f3kis_vpHeFyyEzW).

Important thing about makefiles: absolut paths in Msys style (`/c/dir1/dir2/file22.txt`, `/c/dir1/dir2/dir3`) don't work. You have to change them into "mixed" ones, as they are described in cygpath program (`c:/dir1/dir2/file22.txt`, etc.). Relative (`../dir2/file22.txt`, `my-includes/my-lib1`) paths on the other hand work without problems.

How can I disable strategies during configure? There are only these two options:  `--acle --neon' (which according to CMakeLists are architecture dependant). When it comes to Makefile definitions `-DX86_SSE2_FILL_WINDOW -DX86_SSE4_2_CRC_HASH -DX86_PCLMULQDQ_CRC -DX86_QUICK_STRATEGY'
When I removed `-DX86_SSE2_FILL_WINDOW` I got linker `deflate_quick.c:(.text+0x1c6): undefined reference to 'fill_window_sse'` - it's more integrated than just through `#define`. So I didn't try that.

I also tried to run all compression levels from 1 to 9 and they trigger the same error.
ed: pigz uses zopfli algorithm as a special (-11) strategy and this one doesn't cause the error.
ed#2: updated logs' urls

**Comment by Dead2** [comment] 2018-05-20 13:10
Pigz is kind of a special case, since it uses several threads to speed up compression. I have not looked into how pigz does the threading, but either it does something special that does not work with zlib-ng or we have a thread-safety issue.

**Comment by mtl1979** [comment] 2018-05-20 13:47
For me the assembly listing looks suspicious as it's using MMX registers instead of SSE registers... Mixing both MMX registers and SSE registers in same code can cause issues. As far as I know, zlib-ng is not thread-safe and never has been, so it can't be used in multi-threaded applications on more than 1 thread.

**Comment by cieplutki** [comment] 2018-05-25 01:09
It works in linux (x86 & x64) without any issues and using supposedly same pthread library.
Is it by luck or there is other reason I don't know. But I don't believe that much in blind luck in successful cases - I tried to implement plzip in windows before and replaced pread/pwrite with read/write (+necessary file pointer preservation) and it still didn't work with more than one thread.

About assembly: I can check what it look like in linux but never used any disassembler there. Which shall I use?

**Comment by mtl1979** [comment] 2018-05-25 07:15
There are some fundamental differences between Linux and Windows due to POSIX API in Windows being implemented a long time ago without any updates until Windows 10. Diagnosing the root cause of crash would require putting trace statements all around the code that calls any functions defined in fill_window_sse.c. That way we would know exactly where it crashes and what are the variable or register contents.

**Comment by cieplutki** [comment] 2018-05-28 20:03
I got it working under windows_x64 but my computer had broken and will need serious operation. Can't remember for sure as I'm engaged by this crash but it worked in mingw64-gcc-7.3.0 and with winpthread. I couldn't make this compiler to link against pthread2 no matter what so can't tell if pthread2 is really a problem or compiler or both.
Now, as I'm on old 32-bit again for some time I will try to make it with newest mingw32 and will report.

**Comment by nmoinvaz** [comment] 2020-05-03 00:39
@cieplutki are you able to reproduce this with latest develop?

**Comment by Dead2** [comment] 2020-06-27 10:55
Closing as this is probably fixed now, please reopen if this is still a problem.

**Closed as completed by Dead2** 2020-06-27 10:55 UTC
Labels: bug, help wanted, Investigation needed
