### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by silviucpp** [zlib-ng/zlib-ng#105] opened 2017-04-13 13:10 UTC
Hello,

In my project https://github.com/silviucpp/ezlib/tree/dev I've updated zlibng from 343c4c549107d31f6eeabfb4b31bec4502a2ea0e to 75e76eebeb08dccea44a1d9933699f7f9a0a97ea (last master) and seems when compiled with -O3 it's crashing when try to do 

deflateInit2(stream, 6, Z_DEFLATED, 10, 1, Z_DEFAULT_STRATEGY) 

on different z_stream objects from multiple threads at the same time (I have z_stream objects and try to init each one on it's own thread)

Crash seems to take place in int ZEXPORT deflateResetKeep(z_stream *strm) and the crashing code is EXC_I386_GPFLT

Anything changed between that 2 revisions ? I can't repro this problem on a older revision or in original zlib, cloudlafre or intel fork

Silviu

**Comment by Dead2** [comment] 2017-04-24 10:50
Hi, thank you for the report.

Would you be able to do a git bisect to narrow down the changes?

**Comment by silviucpp** [comment] 2017-04-24 11:01
I'll try to find the commit that broken this. I hope to have some time this week

Silviu

**Comment by Dead2** [comment] 2017-08-17 10:02
Any news on that bisect?

**Comment by mtl1979** [comment] 2017-09-13 12:08
Nothing in deflateResetKeep() should cause crash, most likely the cause of the crash is earlier in call stack. Corrupted z_stream or deflate_state can cause random crashes anywhere due to deflateStateCheck() only checking for NULL pointers and not pointers to unmapped memory.

**Comment by Dead2** [comment] 2018-02-16 19:32
Nothing new for 10 months, closing until new information exists.

**Closed as completed by Dead2** 2018-02-16 19:32 UTC
Labels: bug, information needed
