### ISSUE TITLE
`/usr/libexec/zlib/testsuite` fails with zlib-ng-compat on aarch64

### ISSUE THREAD

**Issue by ggardet** [zlib-ng/zlib-ng#1027] opened 2021-07-20 12:00 UTC
On aarch64, `/usr/libexec/zlib/testsuite` (from zlib) runs properly with regular `zlib`:
```
zlib version 1.2.11 = 0x12b0, compile flags = 0xa9
uncompress(): hello, hello!
gzread(): hello, hello!
gzgets() after gzseek: hello!
inflate(): hello, hello!
large_inflate(): OK
after inflateSync(): hello, hello!
inflate with dictionary: hello, hello!
```
But with `zlib-ng-compat` 2.0.5, we get:
```
warning: different zlib version
zlib version 1.2.11 = 0x12b0, compile flags = 0xa9
uncompress(): hello, hello!
gzread(): hello, hello!
gzgets() after gzseek: hello!
inflate(): hello, hello!
large_inflate(): OK
inflate should report DATA_ERROR
```
I would expect the testsuite from zlib to run properly with zlib-ng in compat mode. Or am I missing something?

The error is likely from https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/test/example.c#L444

**Comment by mtl1979** [comment] 2021-07-20 12:29
That is due to version conflict.
Same error is printed if you mix files from zlib 1.2.11 and zlib 1.2.11.1.

**Comment by ggardet** [comment] 2021-07-20 12:58
> That is due to version conflict.
> Same error is printed if you mix files from zlib 1.2.11 and zlib 1.2.11.1.

I doubt `inflate should report DATA_ERROR` is related to version mismatch.

**Comment by mtl1979** [comment] 2021-07-20 13:00
I compared the differences in the actual source files for the tests (test/example.c).

**Comment by ggardet** [comment] 2021-07-20 13:23
There is indeed a difference on `test/example.c`:
From zlib:
```
    err = inflate(&d_stream, Z_FINISH);
    if (err != Z_DATA_ERROR) {
        fprintf(stderr, "inflate should report DATA_ERROR\n");
        /* Because of incorrect adler32 */
        exit(1);
    }
```
From zlib-ng:
```
    err = PREFIX(inflate)(&d_stream, Z_FINISH);
    if (err != Z_STREAM_END) {
        fprintf(stderr, "inflate should report Z_STREAM_END\n");
        exit(1);
    }
```
EDIT: this is from https://github.com/zlib-ng/zlib-ng/commit/33ce336b82f257689e7d20cee228fa61e079b90a which is zlib 2 (in development)

**Comment by mtl1979** [comment] 2021-07-20 13:36
I compared zlib 1.2.11, zlib 1.2.11.1 and latest zlib-ng... The relevant change was made around 2019, zlib 1.2.11 was released in 2017.

**Comment by ggardet** [comment] 2021-07-20 13:44
> I compared zlib 1.2.11, zlib 1.2.11.1 and latest zlib-ng... The relevant change was made around 2019, zlib 1.2.11 was released in 2017.

I cannot find 1.2.11.1, official homepage + github only shows 1.2.11.  Would you have a link, please?

**Comment by mtl1979** [comment] 2021-07-20 13:50
https://github.com/madler/zlib/tree/develop

**Comment by ggardet** [comment] 2021-07-20 14:03
> https://github.com/madler/zlib/tree/develop

Ah, it is not an official release (it was not even git tagged) and is just part of the dev tree.

**Comment by mtl1979** [comment] 2021-07-20 14:19
Mark Adler has been seriously lazy at maintaining zlib. That's one of the reasons why zlib was forked. Stock zlib doesn't really support modern processors as it was designed for 16-bit and 32-bit processors.

**Comment by ggardet** [comment] 2021-07-20 14:20
So, the test error can be safely ignored, right?

**Comment by mtl1979** [comment] 2021-07-20 14:44
inflateSync() is not used normally to suppress checksum failures, so the error code that is returned after inflateSync() doesn't matter.

**Closed as completed** 2021-12-14 18:39 UTC
