### ISSUE TITLE
Incorporate fast crc32 changes

### ISSUE THREAD

**Issue by arsnyder16** [zlib-ng/zlib-ng#307] opened 2019-02-18 14:30 UTC
Just wanted to forward this information along just so it wasn't missed. Looks like there has been some optimization work done for crc32 that could be applied to zlib-ng 

[Fast CRC32](https://github.com/stbrumme/crc32)

**Comment by mtl1979** [comment] 2019-02-18 14:51
We prefer pull requests with patches against development branch, so we can readily test... I might sound harsh, but zlib-ng is just one of the projects we work on and if we need to manually compare two trees each time someone opens an issue, we will have little time to do anything else.

**Comment by arsnyder16** [comment] 2019-02-18 15:49
I wasn't suggesting this be pulled as is from the other repo.  i just wanted to point out there are some changes in crc32 that could be done for better performance, and that repo could be used as a resource.

**Comment by mtl1979** [comment] 2019-02-18 15:58
I was just pointing out that we don't use other repositories as resources, we use single patches, because usually we need to apply additional patches to the code just to make it even work as it was designed.

**Comment by nmoinvaz** [comment] 2021-07-07 04:23
I ran some google benchmark tests and found that `crc32_16bytes` (defined on fast crc32 website) is twice as slow as `crc32_little` (zlib). Both read data unaligned 32-bit data. I tried using MSVC and ClangCl and tested on Intel Coffee Lake i7-8700.  Also interesting to note that `UNROLL_MORE` stuff had little impact.

```
crc_generic_bench_mean                      17.5 ns         17.5 ns           20
crc_generic_bench_median                    17.3 ns         17.2 ns           20
crc_generic_bench_stddev                   0.859 ns        0.812 ns           20
crc32_little_bench_mean                     7.43 ns         7.42 ns           20
crc32_little_bench_median                   7.42 ns         7.32 ns           20
crc32_little_bench_stddev                  0.138 ns        0.144 ns           20
crc32_little_unroll_more_bench_mean         7.71 ns         7.72 ns           20
crc32_little_unroll_more_bench_median       7.65 ns         7.67 ns           20
crc32_little_unroll_more_bench_stddev      0.183 ns        0.195 ns           20
crc32_16bytes_bench_mean                    16.6 ns         16.6 ns           20
crc32_16bytes_bench_median                  16.5 ns         16.4 ns           20
crc32_16bytes_bench_stddev                 0.281 ns        0.349 ns           20
```
https://gist.github.com/nmoinvaz/637eb77f8314706f2d0bfcc1a0881e77

**Comment by mtl1979** [comment] 2021-07-07 05:53
gcc has changed a lot since 4.7.0... I think `UNROLL_MORE` only improves performance if there is enough available registers, which means architectures like ARM that have instructions to use register ranges instead of single registers. The logic is that the loop does less adjustments to the index variable (due to using combination of index variable and fixed offsets) and that jumping back to start of loop is a lot slower instruction than adjusting (incrementing/decrementing) the index variable.

Modern compilers and processors are smart enough to align the loops so that whole code fits and stays in the processor cache.

**Comment by nmoinvaz** [comment] 2021-12-27 00:30
Is there anything more we want to do here? If not we should close this out.

**Comment by nmoinvaz** [comment] 2022-01-16 19:12
I took another look at this and it seems that the method described in the GitHub repo use a different `crc32` table. I don't think it is something we can implement because we export the `crc32_table`.

**Comment by rurban** [comment] 2022-03-28 18:52
I looked at it. it is only an improvement for SW crc32, but cannot beat our HW assisted variants at all.
the table would be no issue, this can be calculated to use our C variant.

**Comment by nmoinvaz** [comment] 2022-03-28 21:31
SW implementation speed improvements would be good so long as we don't bloat code size with a bunch of different tables.

**Comment by mtl1979** [comment] 2022-03-28 21:46
Having table with 256 entries (8 bits) still takes small amount of space in source file and memory when running, but increasing to 16 or 32 bits already take too much unless we can split them as chunks of 8 bit lookups with insignificant speed penalty.

Only optimization that would not require increasing memory usage would be reordering the instructions so incrementing pointers is avoided as much as possible and offset+index pair is used instead. This is however something that compilers already do at higher optimization levels if the instruction set allows.

**Comment by nmoinvaz** [comment] 2022-06-08 16:47
It looks like we use similar crc32 table values as the fast crc32 now that PR #1268 has been merged.

**Comment by nmoinvaz** [comment] 2022-06-11 23:51
Here are some updated benchmarks where `crc32_braid` is what is currently in zlib-ng and `crc32_16bytes` is the best in the fast crc library:
```
2022-06-11T16:46:27-07:00
Running C:\Users\nathan\Source\zlib-ng\build\test\benchmarks\Release\benchmark_zlib.exe
Run on (12 X 3192 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x6)
  L1 Instruction 32 KiB (x6)
  L2 Unified 256 KiB (x6)
  L3 Unified 12288 KiB (x1)
-------------------------------------------------------------------------
Benchmark                               Time             CPU   Iterations
-------------------------------------------------------------------------
crc32/braid/1                        4.43 ns         4.15 ns    161858065
crc32/braid/1                        9.31 ns         5.89 ns    161858065
crc32/braid/1                        5.41 ns         5.21 ns    161858065
crc32/braid/1                        5.70 ns         4.83 ns    161858065
crc32/braid/1                        4.10 ns         4.05 ns    161858065
crc32/braid/1                        4.03 ns         4.05 ns    161858065
crc32/braid/1                        5.82 ns         4.83 ns    161858065
crc32/braid/1                        4.92 ns         4.73 ns    161858065
crc32/braid/1                        3.43 ns         3.48 ns    161858065
crc32/braid/1                        3.19 ns         3.19 ns    161858065
crc32/braid/1_mean                   5.03 ns         4.44 ns           10
crc32/braid/1_median                 4.68 ns         4.44 ns           10
crc32/braid/1_stddev                 1.75 ns        0.814 ns           10
crc32/braid/8                        17.6 ns         17.4 ns     44800000
crc32/braid/8                        18.6 ns         18.5 ns     44800000
crc32/braid/8                        15.9 ns         16.0 ns     44800000
crc32/braid/8                        15.7 ns         15.7 ns     44800000
crc32/braid/8                        15.4 ns         15.3 ns     44800000
crc32/braid/8                        15.7 ns         15.7 ns     44800000
crc32/braid/8                        16.1 ns         16.4 ns     44800000
crc32/braid/8                        16.6 ns         16.4 ns     44800000
crc32/braid/8                        17.3 ns         17.4 ns     44800000
crc32/braid/8                        15.6 ns         15.7 ns     44800000
crc32/braid/8_mean                   16.5 ns         16.5 ns           10
crc32/braid/8_median                 16.0 ns         16.2 ns           10
crc32/braid/8_stddev                 1.07 ns         1.01 ns           10
crc32/braid/64                       47.8 ns         47.4 ns     11200000
crc32/braid/64                       56.6 ns         55.8 ns     11200000
crc32/braid/64                       50.2 ns         50.2 ns     11200000
crc32/braid/64                       49.5 ns         50.2 ns     11200000
crc32/braid/64                       48.8 ns         48.8 ns     11200000
crc32/braid/64                       51.7 ns         51.6 ns     11200000
crc32/braid/64                       48.4 ns         48.8 ns     11200000
crc32/braid/64                       48.2 ns         47.4 ns     11200000
crc32/braid/64                       48.5 ns         48.8 ns     11200000
crc32/braid/64                       48.7 ns         48.8 ns     11200000
crc32/braid/64_mean                  49.8 ns         49.8 ns           10
crc32/braid/64_median                48.8 ns         48.8 ns           10
crc32/braid/64_stddev                2.64 ns         2.47 ns           10
crc32/braid/512                       186 ns          188 ns      3733333
crc32/braid/512                       198 ns          197 ns      3733333
crc32/braid/512                       202 ns          205 ns      3733333
crc32/braid/512                       216 ns          218 ns      3733333
crc32/braid/512                       206 ns          205 ns      3733333
crc32/braid/512                       215 ns          213 ns      3733333
crc32/braid/512                       215 ns          218 ns      3733333
crc32/braid/512                       205 ns          205 ns      3733333
crc32/braid/512                       209 ns          209 ns      3733333
crc32/braid/512                       199 ns          197 ns      3733333
crc32/braid/512_mean                  205 ns          205 ns           10
crc32/braid/512_median                205 ns          205 ns           10
crc32/braid/512_stddev               9.56 ns         9.55 ns           10
crc32/braid/4096                     1282 ns         1256 ns       560000
crc32/braid/4096                     1357 ns         1367 ns       560000
crc32/braid/4096                     1349 ns         1339 ns       560000
crc32/braid/4096                     1560 ns         1562 ns       560000
crc32/braid/4096                     1228 ns         1228 ns       560000
crc32/braid/4096                     1304 ns         1283 ns       560000
crc32/braid/4096                     1222 ns         1228 ns       560000
crc32/braid/4096                     1268 ns         1256 ns       560000
crc32/braid/4096                     1268 ns         1283 ns       560000
crc32/braid/4096                     1252 ns         1200 ns       560000
crc32/braid/4096_mean                1309 ns         1300 ns           10
crc32/braid/4096_median              1275 ns         1270 ns           10
crc32/braid/4096_stddev              99.1 ns          105 ns           10
crc32/braid/32768                    9555 ns         9626 ns        74667
crc32/braid/32768                    9684 ns         9626 ns        74667
crc32/braid/32768                    9366 ns         9417 ns        74667
crc32/braid/32768                    9679 ns         9626 ns        74667
crc32/braid/32768                   10234 ns        10254 ns        74667
crc32/braid/32768                    9432 ns         9417 ns        74667
crc32/braid/32768                    9978 ns        10045 ns        74667
crc32/braid/32768                    9179 ns         8998 ns        74667
crc32/braid/32768                    9940 ns         9626 ns        74667
crc32/braid/32768                    9497 ns         9626 ns        74667
crc32/braid/32768_mean               9654 ns         9626 ns           10
crc32/braid/32768_median             9617 ns         9626 ns           10
crc32/braid/32768_stddev              319 ns          342 ns           10
crc32/braid/262144                  71774 ns        71150 ns        11200
crc32/braid/262144                  73277 ns        73940 ns        11200
crc32/braid/262144                  81896 ns        79520 ns        11200
crc32/braid/262144                  80524 ns        78125 ns        11200
crc32/braid/262144                  77842 ns        78125 ns        11200
crc32/braid/262144                  89508 ns        89286 ns        11200
crc32/braid/262144                  81529 ns        80915 ns        11200
crc32/braid/262144                  77159 ns        76730 ns        11200
crc32/braid/262144                  78190 ns        76730 ns        11200
crc32/braid/262144                  82317 ns        82310 ns        11200
crc32/braid/262144_mean             79401 ns        78683 ns           10
crc32/braid/262144_median           79357 ns        78125 ns           10
crc32/braid/262144_stddev            5025 ns         4930 ns           10
crc32/braid/2097152                632632 ns       627790 ns          896
crc32/braid/2097152                630680 ns       627790 ns          896
crc32/braid/2097152                607322 ns       610352 ns          896
crc32/braid/2097152                652292 ns       645229 ns          896
crc32/braid/2097152                618195 ns       627790 ns          896
crc32/braid/2097152                617616 ns       610352 ns          896
crc32/braid/2097152                637942 ns       645229 ns          896
crc32/braid/2097152                613264 ns       610352 ns          896
crc32/braid/2097152                622834 ns       592913 ns          896
crc32/braid/2097152                572259 ns       575474 ns          896
crc32/braid/2097152_mean           620504 ns       617327 ns           10
crc32/braid/2097152_median         620515 ns       619071 ns           10
crc32/braid/2097152_stddev          21442 ns        22058 ns           10
crc32/braid/4194304               1216079 ns      1227679 ns          560
crc32/braid/4194304               1157589 ns      1143973 ns          560
crc32/braid/4194304               1157831 ns      1171875 ns          560
crc32/braid/4194304               1157940 ns      1171875 ns          560
crc32/braid/4194304               1288337 ns      1283482 ns          560
crc32/braid/4194304               1217727 ns      1227679 ns          560
crc32/braid/4194304               1259646 ns      1255580 ns          560
crc32/braid/4194304               1196778 ns      1199777 ns          560
crc32/braid/4194304               1173989 ns      1199777 ns          560
crc32/braid/4194304               1172460 ns      1171875 ns          560
crc32/braid/4194304_mean          1199838 ns      1205357 ns           10
crc32/braid/4194304_median        1185383 ns      1199777 ns           10
crc32/braid/4194304_stddev          45613 ns        43225 ns           10
crc32/16bytes/1                      2.52 ns         2.51 ns    280000000
crc32/16bytes/1                      2.49 ns         2.46 ns    280000000
crc32/16bytes/1                      2.52 ns         2.51 ns    280000000
crc32/16bytes/1                      2.44 ns         2.40 ns    280000000
crc32/16bytes/1                      2.54 ns         2.57 ns    280000000
crc32/16bytes/1                      2.52 ns         2.51 ns    280000000
crc32/16bytes/1                      2.46 ns         2.46 ns    280000000
crc32/16bytes/1                      2.65 ns         2.68 ns    280000000
crc32/16bytes/1                      2.88 ns         2.85 ns    280000000
crc32/16bytes/1                      2.88 ns         2.90 ns    280000000
crc32/16bytes/1_mean                 2.59 ns         2.58 ns           10
crc32/16bytes/1_median               2.52 ns         2.51 ns           10
crc32/16bytes/1_stddev              0.163 ns        0.171 ns           10
crc32/16bytes/8                      16.1 ns         16.4 ns     44800000
crc32/16bytes/8                      16.1 ns         16.0 ns     44800000
crc32/16bytes/8                      16.5 ns         16.4 ns     44800000
crc32/16bytes/8                      16.3 ns         16.4 ns     44800000
crc32/16bytes/8                      16.6 ns         16.7 ns     44800000
crc32/16bytes/8                      17.1 ns         17.1 ns     44800000
crc32/16bytes/8                      16.8 ns         16.7 ns     44800000
crc32/16bytes/8                      14.9 ns         15.0 ns     44800000
crc32/16bytes/8                      15.1 ns         15.0 ns     44800000
crc32/16bytes/8                      15.4 ns         15.3 ns     44800000
crc32/16bytes/8_mean                 16.1 ns         16.1 ns           10
crc32/16bytes/8_median               16.2 ns         16.4 ns           10
crc32/16bytes/8_stddev              0.726 ns        0.750 ns           10
crc32/16bytes/64                     26.0 ns         25.7 ns     28000000
crc32/16bytes/64                     26.1 ns         26.2 ns     28000000
crc32/16bytes/64                     25.0 ns         25.1 ns     28000000
crc32/16bytes/64                     25.3 ns         25.7 ns     28000000
crc32/16bytes/64                     25.1 ns         25.1 ns     28000000
crc32/16bytes/64                     25.9 ns         25.7 ns     28000000
crc32/16bytes/64                     25.7 ns         25.7 ns     28000000
crc32/16bytes/64                     25.9 ns         25.7 ns     28000000
crc32/16bytes/64                     25.2 ns         25.1 ns     28000000
crc32/16bytes/64                     26.1 ns         26.2 ns     28000000
crc32/16bytes/64_mean                25.6 ns         25.6 ns           10
crc32/16bytes/64_median              25.8 ns         25.7 ns           10
crc32/16bytes/64_stddev             0.413 ns        0.412 ns           10
crc32/16bytes/512                     205 ns          204 ns      3446154
crc32/16bytes/512                     196 ns          195 ns      3446154
crc32/16bytes/512                     202 ns          199 ns      3446154
crc32/16bytes/512                     200 ns          199 ns      3446154
crc32/16bytes/512                     200 ns          199 ns      3446154
crc32/16bytes/512                     199 ns          199 ns      3446154
crc32/16bytes/512                     197 ns          195 ns      3446154
crc32/16bytes/512                     211 ns          209 ns      3446154
crc32/16bytes/512                     196 ns          199 ns      3446154
crc32/16bytes/512                     198 ns          195 ns      3446154
crc32/16bytes/512_mean                200 ns          199 ns           10
crc32/16bytes/512_median              200 ns          199 ns           10
crc32/16bytes/512_stddev             4.56 ns         4.27 ns           10
crc32/16bytes/4096                   1630 ns         1604 ns       448000
crc32/16bytes/4096                   1608 ns         1604 ns       448000
crc32/16bytes/4096                   1572 ns         1569 ns       448000
crc32/16bytes/4096                   1560 ns         1569 ns       448000
crc32/16bytes/4096                   1566 ns         1535 ns       448000
crc32/16bytes/4096                   1602 ns         1604 ns       448000
crc32/16bytes/4096                   1665 ns         1674 ns       448000
crc32/16bytes/4096                   1717 ns         1709 ns       448000
crc32/16bytes/4096                   1779 ns         1779 ns       448000
crc32/16bytes/4096                   1570 ns         1569 ns       448000
crc32/16bytes/4096_mean              1627 ns         1622 ns           10
crc32/16bytes/4096_median            1605 ns         1604 ns           10
crc32/16bytes/4096_stddev            73.0 ns         75.8 ns           10
crc32/16bytes/32768                 13190 ns        13184 ns        49778
crc32/16bytes/32768                 13904 ns        13811 ns        49778
crc32/16bytes/32768                 12987 ns        13184 ns        49778
crc32/16bytes/32768                 14473 ns        14439 ns        49778
crc32/16bytes/32768                 14523 ns        14439 ns        49778
crc32/16bytes/32768                 13571 ns        13497 ns        49778
crc32/16bytes/32768                 13911 ns        13497 ns        49778
crc32/16bytes/32768                 13948 ns        14125 ns        49778
crc32/16bytes/32768                 12915 ns        12870 ns        49778
crc32/16bytes/32768                 12931 ns        12870 ns        49778
crc32/16bytes/32768_mean            13635 ns        13592 ns           10
crc32/16bytes/32768_median          13738 ns        13497 ns           10
crc32/16bytes/32768_stddev            612 ns          593 ns           10
crc32/16bytes/262144               110582 ns       109863 ns         6400
crc32/16bytes/262144               107624 ns       107422 ns         6400
crc32/16bytes/262144               113303 ns       114746 ns         6400
crc32/16bytes/262144               109164 ns       107422 ns         6400
crc32/16bytes/262144               114967 ns       114746 ns         6400
crc32/16bytes/262144               110975 ns       112305 ns         6400
crc32/16bytes/262144               109080 ns       109863 ns         6400
crc32/16bytes/262144               109473 ns       107422 ns         6400
crc32/16bytes/262144               113399 ns       112305 ns         6400
crc32/16bytes/262144               109492 ns       109863 ns         6400
crc32/16bytes/262144_mean          110806 ns       110596 ns           10
crc32/16bytes/262144_median        110037 ns       109863 ns           10
crc32/16bytes/262144_stddev          2349 ns         2831 ns           10
crc32/16bytes/2097152              865328 ns       871931 ns          896
crc32/16bytes/2097152              838964 ns       819615 ns          896
crc32/16bytes/2097152              862702 ns       854492 ns          896
crc32/16bytes/2097152              871329 ns       837054 ns          896
crc32/16bytes/2097152              857286 ns       854492 ns          896
crc32/16bytes/2097152              862141 ns       854492 ns          896
crc32/16bytes/2097152              859511 ns       854492 ns          896
crc32/16bytes/2097152              869241 ns       871931 ns          896
crc32/16bytes/2097152              848233 ns       837054 ns          896
crc32/16bytes/2097152              887257 ns       889369 ns          896
crc32/16bytes/2097152_mean         862199 ns       854492 ns           10
crc32/16bytes/2097152_median       862421 ns       854492 ns           10
crc32/16bytes/2097152_stddev        13069 ns        20136 ns           10
crc32/16bytes/4194304             1851862 ns      1848493 ns          448
crc32/16bytes/4194304             1792159 ns      1778739 ns          448
crc32/16bytes/4194304             1696847 ns      1674107 ns          448
crc32/16bytes/4194304             1673491 ns      1674107 ns          448
crc32/16bytes/4194304             1700934 ns      1708984 ns          448
crc32/16bytes/4194304             1762731 ns      1778739 ns          448
crc32/16bytes/4194304             1686285 ns      1639230 ns          448
crc32/16bytes/4194304             1747781 ns      1743862 ns          448
crc32/16bytes/4194304             1672114 ns      1674107 ns          448
crc32/16bytes/4194304             1620225 ns      1604353 ns          448
crc32/16bytes/4194304_mean        1720443 ns      1712472 ns           10
crc32/16bytes/4194304_median      1698891 ns      1691546 ns           10
crc32/16bytes/4194304_stddev        68018 ns        74350 ns           10
crc32/pclmulqdq/1                    5.05 ns         5.00 ns    100000000
crc32/pclmulqdq/1                    4.98 ns         4.84 ns    100000000
crc32/pclmulqdq/1                    4.99 ns         5.00 ns    100000000
crc32/pclmulqdq/1                    5.24 ns         5.31 ns    100000000
crc32/pclmulqdq/1                    5.06 ns         5.00 ns    100000000
crc32/pclmulqdq/1                    5.13 ns         5.16 ns    100000000
crc32/pclmulqdq/1                    4.91 ns         4.84 ns    100000000
crc32/pclmulqdq/1                    5.11 ns         5.16 ns    100000000
crc32/pclmulqdq/1                    4.93 ns         5.00 ns    100000000
crc32/pclmulqdq/1                    5.13 ns         5.16 ns    100000000
crc32/pclmulqdq/1_mean               5.05 ns         5.05 ns           10
crc32/pclmulqdq/1_median             5.06 ns         5.00 ns           10
crc32/pclmulqdq/1_stddev            0.103 ns        0.148 ns           10
crc32/pclmulqdq/8                    16.1 ns         16.1 ns     40727273
crc32/pclmulqdq/8                    16.1 ns         16.1 ns     40727273
crc32/pclmulqdq/8                    16.0 ns         15.7 ns     40727273
crc32/pclmulqdq/8                    16.3 ns         16.1 ns     40727273
crc32/pclmulqdq/8                    15.8 ns         15.7 ns     40727273
crc32/pclmulqdq/8                    15.4 ns         15.3 ns     40727273
crc32/pclmulqdq/8                    15.3 ns         15.3 ns     40727273
crc32/pclmulqdq/8                    15.6 ns         15.3 ns     40727273
crc32/pclmulqdq/8                    15.6 ns         15.7 ns     40727273
crc32/pclmulqdq/8                    16.6 ns         16.9 ns     40727273
crc32/pclmulqdq/8_mean               15.9 ns         15.8 ns           10
crc32/pclmulqdq/8_median             15.9 ns         15.7 ns           10
crc32/pclmulqdq/8_stddev            0.429 ns        0.480 ns           10
crc32/pclmulqdq/64                   21.4 ns         21.8 ns     34461538
crc32/pclmulqdq/64                   20.8 ns         20.9 ns     34461538
crc32/pclmulqdq/64                   21.7 ns         21.8 ns     34461538
crc32/pclmulqdq/64                   21.3 ns         21.3 ns     34461538
crc32/pclmulqdq/64                   21.6 ns         21.3 ns     34461538
crc32/pclmulqdq/64                   20.7 ns         20.9 ns     34461538
crc32/pclmulqdq/64                   20.7 ns         20.4 ns     34461538
crc32/pclmulqdq/64                   21.2 ns         21.3 ns     34461538
crc32/pclmulqdq/64                   21.2 ns         21.3 ns     34461538
crc32/pclmulqdq/64                   21.4 ns         21.3 ns     34461538
crc32/pclmulqdq/64_mean              21.2 ns         21.2 ns           10
crc32/pclmulqdq/64_median            21.3 ns         21.3 ns           10
crc32/pclmulqdq/64_stddev           0.359 ns        0.417 ns           10
crc32/pclmulqdq/512                  39.0 ns         39.2 ns     17920000
crc32/pclmulqdq/512                  39.4 ns         40.1 ns     17920000
crc32/pclmulqdq/512                  39.4 ns         39.2 ns     17920000
crc32/pclmulqdq/512                  39.4 ns         39.2 ns     17920000
crc32/pclmulqdq/512                  39.5 ns         39.2 ns     17920000
crc32/pclmulqdq/512                  39.0 ns         39.2 ns     17920000
crc32/pclmulqdq/512                  38.5 ns         39.2 ns     17920000
crc32/pclmulqdq/512                  41.4 ns         41.0 ns     17920000
crc32/pclmulqdq/512                  39.3 ns         38.4 ns     17920000
crc32/pclmulqdq/512                  40.9 ns         41.0 ns     17920000
crc32/pclmulqdq/512_mean             39.6 ns         39.6 ns           10
crc32/pclmulqdq/512_median           39.4 ns         39.2 ns           10
crc32/pclmulqdq/512_stddev          0.889 ns        0.842 ns           10
crc32/pclmulqdq/4096                  190 ns          188 ns      3733333
crc32/pclmulqdq/4096                  183 ns          184 ns      3733333
crc32/pclmulqdq/4096                  194 ns          193 ns      3733333
crc32/pclmulqdq/4096                  198 ns          201 ns      3733333
crc32/pclmulqdq/4096                  200 ns          201 ns      3733333
crc32/pclmulqdq/4096                  190 ns          184 ns      3733333
crc32/pclmulqdq/4096                  193 ns          193 ns      3733333
crc32/pclmulqdq/4096                  199 ns          197 ns      3733333
crc32/pclmulqdq/4096                  187 ns          188 ns      3733333
crc32/pclmulqdq/4096                  186 ns          184 ns      3733333
crc32/pclmulqdq/4096_mean             192 ns          191 ns           10
crc32/pclmulqdq/4096_median           192 ns          190 ns           10
crc32/pclmulqdq/4096_stddev          5.75 ns         6.56 ns           10
crc32/pclmulqdq/32768                1356 ns         1350 ns       497778
crc32/pclmulqdq/32768                1477 ns         1444 ns       497778
crc32/pclmulqdq/32768                1375 ns         1381 ns       497778
crc32/pclmulqdq/32768                1366 ns         1350 ns       497778
crc32/pclmulqdq/32768                1447 ns         1413 ns       497778
crc32/pclmulqdq/32768                1614 ns         1601 ns       497778
crc32/pclmulqdq/32768                1777 ns         1758 ns       497778
crc32/pclmulqdq/32768                1793 ns         1758 ns       497778
crc32/pclmulqdq/32768                1543 ns         1507 ns       497778
crc32/pclmulqdq/32768                1425 ns         1444 ns       497778
crc32/pclmulqdq/32768_mean           1517 ns         1500 ns           10
crc32/pclmulqdq/32768_median         1462 ns         1444 ns           10
crc32/pclmulqdq/32768_stddev          163 ns          155 ns           10
crc32/pclmulqdq/262144              12154 ns        12207 ns        64000
crc32/pclmulqdq/262144              11546 ns        11719 ns        64000
crc32/pclmulqdq/262144              11302 ns        11230 ns        64000
crc32/pclmulqdq/262144              11170 ns        11230 ns        64000
crc32/pclmulqdq/262144              12187 ns        12207 ns        64000
crc32/pclmulqdq/262144              11426 ns        11230 ns        64000
crc32/pclmulqdq/262144              11427 ns        11475 ns        64000
crc32/pclmulqdq/262144              10947 ns        10986 ns        64000
crc32/pclmulqdq/262144              11504 ns        11475 ns        64000
crc32/pclmulqdq/262144              12245 ns        12207 ns        64000
crc32/pclmulqdq/262144_mean         11591 ns        11597 ns           10
crc32/pclmulqdq/262144_median       11466 ns        11475 ns           10
crc32/pclmulqdq/262144_stddev         452 ns          464 ns           10
crc32/pclmulqdq/2097152             99129 ns        98349 ns         7467
crc32/pclmulqdq/2097152             97766 ns        98349 ns         7467
crc32/pclmulqdq/2097152             90635 ns        89979 ns         7467
crc32/pclmulqdq/2097152             93452 ns        92072 ns         7467
crc32/pclmulqdq/2097152             93121 ns        92072 ns         7467
crc32/pclmulqdq/2097152             90166 ns        89979 ns         7467
crc32/pclmulqdq/2097152            100332 ns       100442 ns         7467
crc32/pclmulqdq/2097152             96407 ns        96257 ns         7467
crc32/pclmulqdq/2097152             95921 ns        94164 ns         7467
crc32/pclmulqdq/2097152             97535 ns        98349 ns         7467
crc32/pclmulqdq/2097152_mean        95447 ns        95001 ns           10
crc32/pclmulqdq/2097152_median      96164 ns        95211 ns           10
crc32/pclmulqdq/2097152_stddev       3476 ns         3846 ns           10
crc32/pclmulqdq/4194304            208129 ns       208575 ns         3446
crc32/pclmulqdq/4194304            207978 ns       204041 ns         3446
crc32/pclmulqdq/4194304            202299 ns       199507 ns         3446
crc32/pclmulqdq/4194304            202832 ns       204041 ns         3446
crc32/pclmulqdq/4194304            207162 ns       204041 ns         3446
crc32/pclmulqdq/4194304            207555 ns       194972 ns         3446
crc32/pclmulqdq/4194304            203701 ns       204041 ns         3446
crc32/pclmulqdq/4194304            193836 ns       194972 ns         3446
crc32/pclmulqdq/4194304            204199 ns       204041 ns         3446
crc32/pclmulqdq/4194304            198908 ns       199507 ns         3446
crc32/pclmulqdq/4194304_mean       203660 ns       201774 ns           10
crc32/pclmulqdq/4194304_median     203950 ns       204041 ns           10
crc32/pclmulqdq/4194304_stddev       4570 ns         4406 ns           10
```

**Comment by nmoinvaz** [comment] 2022-06-11 23:53
What is in zlib and now in zlib-ng is faster than what the fast crc32 library provides so I am closing this issue.

**Closed as completed by nmoinvaz** 2022-06-11 23:53 UTC
Labels: optimization, Feature Request
