### ISSUE TITLE
`libz-ng.a` and `libz.a` from zlib-compat mode have symbol conflicts

### ISSUE THREAD

**Issue by joshtriplett** [zlib-ng/zlib-ng#1279] opened 2022-05-30 03:50 UTC
zlib-ng in native mode avoids symbol conflicts with stock zlib, but still has symbol conflicts with zlib supplied from zlib-ng built in zlib-compat mode.

This can cause an issue in a few different scenarios:
- If a distribution uses zlib-ng in zlib-compat mode as its system zlib, and an application statically links native zlib-ng but also links a library (such as a system library) that links to zlib, expecting them not to conflict.
- If an application uses native zlib-ng, but has many dependencies, one of which uses zlib-ng in zlib-compat mode (e.g. because it needs to link a C library that needs zlib symbols but wants the performance of zlib-ng).

One instance of this manifested as these link errors:

```
  = note: liblibz_ng_sys-fb58de474afbb4a4.rlib(inflate.obj) : error LNK2005: fixedtables already defined in liblibz_sys-38cf6ff5b07be7a7.rlib(inflate.obj)
          liblibz_ng_sys-fb58de474afbb4a4.rlib(crc32_braid.obj) : error LNK2005: crc32_braid already defined in liblibz_sys-38cf6ff5b07be7a7.rlib(crc32_braid.obj)
          liblibz_ng_sys-fb58de474afbb4a4.rlib(zutil.obj) : error LNK2005: z_error already defined in liblibz_sys-38cf6ff5b07be7a7.rlib(zutil.obj)
          liblibz_ng_sys-fb58de474afbb4a4.rlib(zutil.obj) : error LNK2005: zlibng_version already defined in liblibz_sys-38cf6ff5b07be7a7.rlib(zutil.obj)
          liblibz_ng_sys-fb58de474afbb4a4.rlib(zutil.obj) : error LNK2005: zng_alloc_aligned already defined in liblibz_sys-38cf6ff5b07be7a7.rlib(zutil.obj)
          liblibz_ng_sys-fb58de474afbb4a4.rlib(zutil.obj) : error LNK2005: zng_calloc already defined in liblibz_sys-38cf6ff5b07be7a7.rlib(zutil.obj)
          liblibz_ng_sys-fb58de474afbb4a4.rlib(zutil.obj) : error LNK2005: zng_cfree already defined in liblibz_sys-38cf6ff5b07be7a7.rlib(zutil.obj)
          liblibz_ng_sys-fb58de474afbb4a4.rlib(zutil.obj) : error LNK2005: zng_free_aligned already defined in liblibz_sys-38cf6ff5b07be7a7.rlib(zutil.obj)
          liblibz_ng_sys-fb58de474afbb4a4.rlib(zutil.obj) : error LNK2005: z_verbose already defined in liblibz_sys-38cf6ff5b07be7a7.rlib(zutil.obj)
          liblibz_ng_sys-fb58de474afbb4a4.rlib(zutil.obj) : error LNK2005: zlibng_string already defined in liblibz_sys-38cf6ff5b07be7a7.rlib(zutil.obj)
```

I think this could be fixed with three steps:

1) For the symbols like `fixedtables` and `crc32_braid`, prefix them with `zng_` when not building in zlib-compat mode.
2) For symbols like `zlibng_version`, don't define them at all in zlib-compat mode.
2) For symbols like `zng_alloc_aligned`, prefix them differently (e.g. `zngcompat_alloc_aligned`) when building in zlib-compat mode.

This could also be addressed by hiding some of those symbols, if possible.

(Note that the issue above manifested on Windows, and I couldn't reproduce it on Linux, so it's possible it's specific to either the Windows build of zlib-ng or to behavior of the Windows linker.)

**Comment by mtl1979** [comment] 2022-05-30 08:28
No new binary should ever link against two copies of zlib-ng with different compiler flags... It's expected to fail and is by design. Even if we prefix every single symbol, the result is still something we should discourage.

**Comment by Dead2** [comment] 2022-05-30 15:21
The scenario @joshtriplett describes is a quite common (and very annoying one) when building packages, and I can absolutely see myself hitting that one.

Lets say you want to build application NN with zlib-ng-native, and its dependency-tree has a ton of libraries, and one or more tightly system-integrated libraries depends on zlib-nb-compat.
Been there, done a very similar dance multiple times when wanting to build an updated application that requires a few updated libraries but somewhere in there you have a dependency for a non-updated library or otherwise conflicting one. Both ImageMagick and Curl comes to mind..

As for the suggested solutions:
1. Not a huge fan of prefixing everything with macros, but this would work.
2. I'd like the zlib-ng version to be available to the application somehow even in compat mode without breaking compatibility with existing applications. Not sure about this one, but perhaps a different prefix.
3. `zngc_` prefix or something would work.

Hiding the symbols would be the ideal solution, I wonder why they are not already. zng_cfee (and others on the list above) use the Z_INTERNAL macro, that is supposed to use the internal hint or fall back to the hidden hint, effectively making sure this symbol is hidden from other applications. How was the errors above hit? Like described above an app linking zlib-ng-native and a library that already used zlib-ng-compat, both dynamically? Or are either library linked statically or both directly into the same application? It is my understanding that this scenario should not happen when doing dynamic linking (for the internal/hidden symbols that is).

Linking both directly into the same application is more likely to cause problems of course, and I'm not sure that is actually something worth doing (why would anyone need to? Even for benchmarking it does not really make sense to load both into the same binary at the same time).

**Comment by mtl1979** [comment] 2022-05-30 15:38
Some of the symbols are specific to zlib 1.2.12 and will be fixed when we declare compatibility with the new API... Some might very well be due to bad compiler flags or incompatible compiler/linker versions.

**Comment by joshtriplett** [comment] 2022-05-30 19:08
> Lets say you want to build application NN with zlib-ng-native, and its dependency-tree has a ton of libraries, and one or more tightly system-integrated libraries depends on zlib-nb-compat. Been there, done a very similar dance multiple times when wanting to build an updated application that requires a few updated libraries but somewhere in there you have a dependency for a non-updated library or otherwise conflicting one. Both ImageMagick and Curl comes to mind..

This is exactly the kind of scenario I'm running into. In my case, some of the libraries requiring zlib support are curl and libgit2, and I'd like both to use zlib-ng in zlib-compat mode for performance, but I'm also slowly (and incrementally) migrating to other dependencies that can natively use zlib-ng.

>     2. I'd like the zlib-ng version to be available to the application somehow even in compat mode without breaking compatibility with existing applications. Not sure about this one, but perhaps a different prefix.

Fair enough; would `zngc_zlibng_version` work for that?

>     3. `zngc_` prefix or something would work.

:+1:

> Hiding the symbols would be the ideal solution, I wonder why they are not already. zng_cfee (and others on the list above) use the Z_INTERNAL macro, that is supposed to use the internal hint or fall back to the hidden hint, effectively making sure this symbol is hidden from other applications.

As far as I can tell, `Z_INTERNAL` exclusively uses `__attribute__((visibility(...)))`, which doesn't work when compiling for MSVC. I don't know if there's an MSVC-compatible mechanism for hiding symbols in static libraries (other than combining source files and using `static`, which doesn't seem ideal).

> How was the errors above hit? Like described above an app linking zlib-ng-native and a library that already used zlib-ng-compat, both dynamically? Or are either library linked statically or both directly into the same application? It is my understanding that this scenario should not happen when doing dynamic linking (for the internal/hidden symbols that is).

I was building a Rust application, which was statically linking in all its libraries. I pulled in multiple different crates; one could use zlib-ng in native mode because it had native support, while others (curl) needed zlib compatibility. I'd like to be able to incrementally migrate to using native support.

I'm one of the maintainers of libz-sys (which supports both zlib and zlib-ng in zlib-compat mode) and libz-ng-sys (which uses zlib-ng natively) in the Rust ecosystem. I'm trying to migrate some libraries from only supporting the former to also supporting the latter when possible. I'm expecting that migration to be incremental and gradual, and any crates providing C library bindings would have to wait for the underlying C library to support using zlib-ng natively (which curl and libgit2 don't yet). For that reason, I'd like to be able to ensure that 1) crates providing C library bindings that need zlib can offer the option of using zlib-ng-compat for performance, and 2) crates that support zlib-ng natively can use zlib-ng natively.

**Comment by mtl1979** [comment] 2022-05-30 20:50
The correct way to handle is to use either statically or dynamically linked wrapper library that links dynamically to zlib-ng... This is how I do cross-language wrappers in my other projects... If there is still symbol conflicts, those should be handled with the existing symbol prefixing feature.

There will be a lot of intentional symbol conflicts when statically linking against multiple copies of zlib-ng.

**Comment by joshtriplett** [comment] 2022-05-31 05:56
Using the symbol prefix feature would make those libraries incompatible with C code that's expecting either the zlib API or the native zlib-ng API. And in any case, the symbol prefixing feature doesn't appear to prefix the symbols I encountered symbol conflicts with.

**Comment by nmoinvaz** [comment] 2022-06-19 06:16
I have put together a GHA workflow that reproduces the issue:
https://github.com/nmoinvaz/zlib-ng/blob/improvements/dual-link-test/.github/workflows/link.yml

CI run:
https://github.com/nmoinvaz/zlib-ng/runs/6953216938?check_suite_focus=true

Output:
```c
[100%] Linking CXX executable gtest_zlib
/usr/bin/ld: ../libz-ng.a(crc32_braid.c.o): in function `crc32_braid':
crc32_braid.c:(.text+0x60): multiple definition of `crc32_braid'; ../../compat/libz.a(crc32_braid.c.o):crc32_braid.c:(.text+0x70): first defined here
/usr/bin/ld: ../libz-ng.a(deflate.c.o): in function `read_buf':
deflate.c:(.text+0x1a50): multiple definition of `read_buf'; ../../compat/libz.a(deflate.c.o):deflate.c:(.text+0x1a40): first defined here
/usr/bin/ld: ../libz-ng.a(deflate.c.o): in function `fill_window':
deflate.c:(.text+0x1ae0): multiple definition of `fill_window'; ../../compat/libz.a(deflate.c.o):deflate.c:(.text+0x1ae0): first defined here
/usr/bin/ld: ../libz-ng.a(inflate.c.o): in function `fixedtables':
inflate.c:(.text+0x460): multiple definition of `fixedtables'; ../../compat/libz.a(inflate.c.o):inflate.c:(.text+0x450): first defined here
/usr/bin/ld: ../libz-ng.a(zutil.c.o): in function `zng_calloc':
zutil.c:(.text+0x0): multiple definition of `zng_calloc'; ../../compat/libz.a(zutil.c.o):zutil.c:(.text+0x0): first defined here
/usr/bin/ld: ../libz-ng.a(zutil.c.o): in function `zng_cfree':
zutil.c:(.text+0x60): multiple definition of `zng_cfree'; ../../compat/libz.a(zutil.c.o):zutil.c:(.text+0x60): first defined here
/usr/bin/ld: ../libz-ng.a(zutil.c.o): in function `zlibng_version':
zutil.c:(.text+0x70): multiple definition of `zlibng_version'; ../../compat/libz.a(zutil.c.o):zutil.c:(.text+0x80): first defined here
/usr/bin/ld: ../libz-ng.a(zutil.c.o): in function `zng_alloc_aligned':
zutil.c:(.text+0xb0): multiple definition of `zng_alloc_aligned'; ../../compat/libz.a(zutil.c.o):zutil.c:(.text+0xc0): first defined here
/usr/bin/ld: ../libz-ng.a(zutil.c.o): in function `zng_free_aligned':
zutil.c:(.text+0x160): multiple definition of `zng_free_aligned'; ../../compat/libz.a(zutil.c.o):zutil.c:(.text+0x170): first defined here
/usr/bin/ld: ../libz-ng.a(zutil.c.o):(.rodata+0x0): multiple definition of `zlibng_string'; ../../compat/libz.a(zutil.c.o):(.rodata+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/gtest_zlib.dir/build.make:516: test/gtest_zlib] Error 1
make[1]: *** [CMakeFiles/Makefile2:403: test/CMakeFiles/gtest_zlib.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by nmoinvaz** [comment] 2022-06-19 06:22
What is strange to me is that it has a problem with `crc32_braid` but it does not have a problem with `compare256_c`. Both functions are defined very much the same...

I think perhaps the difference is that `crc32_braid` is used in multiple source files where as `compare256_c` is only used in one.

**Comment by mtl1979** [comment] 2022-06-21 10:10
When multiple object files need a symbol with same name, the lookup is done sequentially from the point where the symbol is used. This means any previous definitions will be ignored until the final phase of the linking. This is issue that happens only with static archives, as symbols in shared libraries are resolved at runtime.

For some symbols this is not an issue as they are required from either the startup object files inserted by compiler, or the first `main` function in the resulting executable (called from the startup object files).

**Comment by nmoinvaz** [comment] 2023-01-13 17:55
@joshtriplett this should be merged into develop now.

**Comment by nmoinvaz** [comment] 2023-02-05 19:28
Closing, should be resolved in develop.

**Closed as completed by nmoinvaz** 2023-02-05 19:28 UTC
